### PR TITLE
fix no audio due to wrong buffer

### PR DESCRIPTION
**Pull request by KnappSas**
I experienced no audible feedback after I was finally able to build the project. I had to change the order of includes for this. To fix the missing audio I had to change the deviceBuffer to userBuffer when converting the callback buffer.

### CODE REVIEW

**Comment by MarcusTomlinson** [comment]
Sorry for leaving you hanging with this. This is the actual fix required for the issue you were experiencing: https://github.com/MarcusTomlinson/rtaudio/commit/bf7e1a2c60d9267c05000f429926627b9a87ef78

Which is in my master branch. Still not merged upstream though due to some MingW build issues.

**Comment by KnappSas** [comment]
@MarcusTomlinson  Yea this is still not working for me I'm afraid.
Still no audio output. I found out that your changes in https://github.com/MarcusTomlinson/rtaudio/commit/fe5acf0320a836220a5f3e6bf2b3a598859509e5 prevent me from entering :

```
if ( stream_.doConvertBuffer[OUTPUT] )
{
     // Convert callback buffer to stream format
     convertBuffer( stream_.deviceBuffer,
                stream_.userBuffer[OUTPUT],
                stream_.convertInfo[OUTPUT] );
}     
```
If I revert those changes it only works with 44,1 kHz and 48 kHz. :(

**Comment by MarcusTomlinson** [comment]
Odd. You’re using my master branch? (https://github.com/MarcusTomlinson/rtaudio)

**Comment by KnappSas** [comment]
Yes. I also still run into the problem that I have to change the order of the includes to make it build successfully. I'm using Visual Studio 2017 on Windows 10.

**Comment by MarcusTomlinson** [comment]
> Yes. I also still run into the problem that I have to change the order of the includes to make it build successfully. I'm using Visual Studio 2017 on Windows 10.

Hey @KnappSas, I _may_ have found a fix to this ^ issue you were telling me about.

I managed to reproduce a no audio condition by running WASAPI in interleaved mode, in the audio device's native format (in my case float32).

This fixes it: https://github.com/thestk/rtaudio/pull/175

**Pull request closed without merging**
